name: Kwiki-Theme-Bluepole
version: 1.00
abstract: A nice, blue Kwiki Theme
author: Jon Åslund <aslund.org>
license: perl
distribution_type: module
requires:
  perl: 5.6.1
  Kwiki: 0.34
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.34
